// automatically generated by the FlatBuffers compiler, do not modify

package com.tlongdev.bktf.flatbuffers.prices;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Prices extends Table {
  public static Prices getRootAsPrices(ByteBuffer _bb) { return getRootAsPrices(_bb, new Prices()); }
  public static Prices getRootAsPrices(ByteBuffer _bb, Prices obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Prices __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Price prices(int j) { return prices(new Price(), j); }
  public Price prices(Price obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int pricesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createPrices(FlatBufferBuilder builder,
      int pricesOffset) {
    builder.startObject(1);
    Prices.addPrices(builder, pricesOffset);
    return Prices.endPrices(builder);
  }

  public static void startPrices(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addPrices(FlatBufferBuilder builder, int pricesOffset) { builder.addOffset(0, pricesOffset, 0); }
  public static int createPricesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startPricesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endPrices(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishPricesBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

