// automatically generated by the FlatBuffers compiler, do not modify

package com.tlongdev.bktf.flatbuffers.itemschema;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Item extends Table {
  public static Item getRootAsItem(ByteBuffer _bb) { return getRootAsItem(_bb, new Item()); }
  public static Item getRootAsItem(ByteBuffer _bb, Item obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Item __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int defindex() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String name() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public String description() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer descriptionAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public String type() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer typeAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public boolean proper() { int o = __offset(12); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public String image() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer imageAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public String imageLarge() { int o = __offset(16); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer imageLargeAsByteBuffer() { return __vector_as_bytebuffer(16, 1); }

  public static int createItem(FlatBufferBuilder builder,
      int defindex,
      int nameOffset,
      int descriptionOffset,
      int typeOffset,
      boolean proper,
      int imageOffset,
      int imageLargeOffset) {
    builder.startObject(7);
    Item.addImageLarge(builder, imageLargeOffset);
    Item.addImage(builder, imageOffset);
    Item.addType(builder, typeOffset);
    Item.addDescription(builder, descriptionOffset);
    Item.addName(builder, nameOffset);
    Item.addDefindex(builder, defindex);
    Item.addProper(builder, proper);
    return Item.endItem(builder);
  }

  public static void startItem(FlatBufferBuilder builder) { builder.startObject(7); }
  public static void addDefindex(FlatBufferBuilder builder, int defindex) { builder.addInt(0, defindex, 0); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(1, nameOffset, 0); }
  public static void addDescription(FlatBufferBuilder builder, int descriptionOffset) { builder.addOffset(2, descriptionOffset, 0); }
  public static void addType(FlatBufferBuilder builder, int typeOffset) { builder.addOffset(3, typeOffset, 0); }
  public static void addProper(FlatBufferBuilder builder, boolean proper) { builder.addBoolean(4, proper, false); }
  public static void addImage(FlatBufferBuilder builder, int imageOffset) { builder.addOffset(5, imageOffset, 0); }
  public static void addImageLarge(FlatBufferBuilder builder, int imageLargeOffset) { builder.addOffset(6, imageLargeOffset, 0); }
  public static int endItem(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

