// automatically generated by the FlatBuffers compiler, do not modify

package com.tlongdev.bktf.flatbuffers.itemschema;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Origin extends Table {
  public static Origin getRootAsOrigin(ByteBuffer _bb) { return getRootAsOrigin(_bb, new Origin()); }
  public static Origin getRootAsOrigin(ByteBuffer _bb, Origin obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Origin __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int id() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String name() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }

  public static int createOrigin(FlatBufferBuilder builder,
      int id,
      int nameOffset) {
    builder.startObject(2);
    Origin.addName(builder, nameOffset);
    Origin.addId(builder, id);
    return Origin.endOrigin(builder);
  }

  public static void startOrigin(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addId(FlatBufferBuilder builder, int id) { builder.addInt(0, id, 0); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(1, nameOffset, 0); }
  public static int endOrigin(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

